import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { off } from "process";
import { useEffect, useState } from "react";

type pokemonApiResponseType = {
  count: number;
  next: string;
  previous: string | null;
  results: { name: string; url: string }[];
};

const Home: NextPage = () => {
  const [pokemon, setPokemon] = useState<pokemonApiResponseType>();
  const [offset, setOffset] = useState(0);

  useEffect(() => {
    const getPokemon = async () => {
      try {
        const resp = await fetch(
          `https://pokeapi.co/api/v2/pokemon/?offset=${offset}&limit=16`
        );
        setPokemon(await resp.json());
      } catch (error) {
        console.log("Failed to load poki");
      }
    };
    getPokemon();
  }, [offset]);

  const handleNextOffset = () => {
    if (offset < 1100) {
      setOffset((prev) => prev + 16);
    }
  };
  const handlePrevOffset = () => {
    if (offset > 0) {
      setOffset((prev) => prev - 16);
    }
  };

  return (
    <div className="">
      <Head>
        <title>Cozy's Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-full w-full items-center flex-col">
        <div className="container flex flex-col items-center text-center">
          <h1 className="text-3xl text-sky-500 hover:text-red-500 my-8 duration-200">
            Cozy's Pokedex
          </h1>
          <p className="text-xl text-slate-800 mb-8">
            The Pokédex contains detailed stats for every creature from the
            Pokemon games.
          </p>
        </div>
        <div className="container lg:px-16">
          <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 h-full gap-4 items-center">
            {pokemon?.results.map((item, i) => (
              <li key={i} className="flex justify-center items-center ">
                <Link className="" href={`pokemon/${item.name}`}>
                  <div className=" hover:bg-slate-100 hover:shadow border rounded-lg p-4 duration-200 active:bg-slate-200">
                    <div className="flex flex-col items-center">
                      <img
                        className="w-40"
                        src={
                          "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" +
                          (i + offset + 1).toString() +
                          ".png"
                        }
                        alt={item.name}
                      />
                      <p className="capitalize-first">{item.name}</p>
                    </div>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
          <div className="flex items-center justify-center gap-4 py-10">
            {offset > 15 && (
              <button
                className="px-4 py-2 bg-blue-500 active:bg-blue-600 text-white rounded-lg"
                onClick={handlePrevOffset}
              >
                Prev Page
              </button>
            )}
            <button
              className="px-4 py-2 bg-red-500 active:bg-red-600 text-white rounded-lg"
              onClick={handleNextOffset}
            >
              Next Page
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
